[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist',
    'npm ci --no-audit',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan config:clear',
    'php artisan route:clear',
    'php artisan view:clear',
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
