[build]
builder = "nixpacks"
buildCommand = "composer install --optimize-autoloader --no-dev && npm ci && npm run build"

[deploy]
startCommand = "php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
